package ua.kp13.mishchenko;

public enum TokenType {
	NUMBER, VARIABLE, STRING, FALSE, TRUE,
	OPER_AND, OPER_OR, OPER_NOT, OPER_IS, OPER_LESS, OPER_MORE, OPER_LESS_EQUALS, OPER_MORE_EQUALS, OPER_IS_NOT,
	OPER_EQUALS, OPER_PLUS, OPER_MINUS, OPER_MULTIPLY, OPER_DIVISION, OPER_POWER,
	TYPE_INT, TYPE_STRING, TYPE_FLOAT, TYPE_BOOLEAN, NEXT_LINE,
	FLOATING_POINT, DOUBLE_QUOTES,
	BRACKET_CURLY_OPENED, BRACKET_CURLY_CLOSED, BRACKET_OPENED, BRACKET_CLOSED,
	IF, ELIF, ELSE
} 
